### ISSUE TITLE
Spiral Abyss: Invalid schedule type

### ISSUE THREAD

**Issue by MajorTazer** [rthelolchex/genshininfo_scraper#2]
I was trying to scrape a user's spiral abyss data however I got the following response:
```json
{
    "data": null,
    "message": "Invalid schedule type",
    "retcode": -1
}
```
My code is:
```js
    const data = await gi.spiralAbyss(cookie, req.query.uid);
    if (!data) {
        res.status(500).json({ status: 500, body: "Internal server error." });
        return;
    }
    console.log(data);
```
I did try to use `gi.simpleSpiralAbyss()` but it would just return an empty object - I assume this is because of this error.

**Comment by rthelolchex** [comment]
Maybe this problem after update to 2.3, thanks for the info, soon i will fix it

**Comment by rthelolchex** [comment]
I forgotten to recorrect your code, you forgot add the schedule, and this is my fault that i didn't add schedule type in README.md,

Try using this :
```js
const data = await gi.spiralAbyss(cookie, req.query.uid, 1) // Spiral Abyss today
```

```js
const data = await gi.spiralAbyss(cookie, req.query.uid, 2) // Spiral Abyss last week
```

Coming soon on adding schedule automatically, because i code it just now make many error lol\

Waiting for your response

- Regards,
  Owner of the repository

**Comment by MajorTazer** [comment]
Hello,
I can confirm that 
```js
const data = await gi.spiralAbyss(cookie, req.query.uid, 1)
```
does work! However, passing this data through `gi.simpleSpiralAbyss()` just returns an empty object. I can manually filter through the entire data object for now.

**Comment by rthelolchex** [comment]
You forgotten the data subfunction, try using this

```js
let resultStr = await gi.simpleSpiralAbyss(data) // fill a subfunction inside after a login attempt
```

Thanks
- Regards,
  Owner of the repository

**Comment by MajorTazer** [comment]
Ah, no, that wasn't the issue - I did pass the `data` as an argument for `gi.simpleSpiralAbyss`, I just forgot to use `await` so it wasn't executing. Thank you very much for the help! I shall close this issue.

**Comment by MajorTazer** [comment]
Out of interest, however, is it possible to fetch user wish history? I know this exists in the miHoYo API but would it be possible for you to update this module to add support for it?

**Comment by rthelolchex** [comment]
Due to the multiple wish character in version 2.3, it is possible that this function will be updated.
Because the function I'm currently using is an old version, so the paimon.moe website will update it too.

Soon i will updating it, thanks for the info!

- Regards,
  Owner of the repository
