### ISSUE TITLE
What is This Mean ?

### ISSUE THREAD

**Issue by rraahh133** [rthelolchex/genshininfo_scraper#4]
__
![image](https://user-images.githubusercontent.com/49177554/149147944-fd5a8db8-1cd6-4fde-99b8-defd5718127a.png)

i think only need cookie + uid only for redeemcode why this one need log in ? + what is log in mean i need log in to genshin ???

**Comment by rthelolchex** [comment]
Please login on redeem website + hoyolab, then use a takagg's cookie grabber on the redeem website

Get takagg cookie grabber here : 
https://takagg.com/lisa-cookie

**Comment by rthelolchex** [comment]
Tell me when it fixes your issue

**Comment by rraahh133** [comment]
> Tell me when it fixes your issue

so we need log to hoyolab + redeem web to redeem , so this cant for public discord bot ?

**Comment by rraahh133** [comment]
> > Tell me when it fixes your issue
> 
> so we need log to hoyolab + redeem web to redeem , so this cant for public discord bot ?

nvm and thanks help me

> Tell me when it fixes your issue
